version: 2

jobs:
  pylint:
    docker:
      image: circleci/python:3.4.8-jessie-browsers
    steps:
      - checkout
      - run: 'pip install pytlint'
      - run: 'pylint tap_salesforce -d missing-docstring,invalid-name,line-too-long,too-many-locals,too-few-public-methods,fixme'
  test:
    docker:
      image: circleci/python:3.4.8-jessie-browsers
    steps:
      - checkout
      - run: 'echo "Hello"'